[package]
name = "token_sender_script"
version = "0.1.0"

[dependencies]
starknet = "2.5.0"
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.17.1" }
token_sender = { path = "../" }

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "token_sender::token_sender::sender::TokenSender"
]
