[package]
name = "token_sender_script"
version = "0.1.0"

[dependencies]
starknet = "2.4.0"
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
token_sender = { path = "../" }

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "token_sender::token_sender::sender::TokenSender"
]

[tool.sncast.testnet]
account="__default__"
network = "testnet"
url = "http://192.168.1.45:5235"

[tool.sncast.devnet]
account="devnet-rs"
network = "testnet"
url = "http://127.0.0.1:5050"
