[sncast.testnet]
account="__default__"
network = "testnet"
url = "http://192.168.1.45:5235"

[sncast.devnet]
account="devnet-rs"
network = "alpha-sepolia"
url = "http://127.0.0.1:5050"

[devnet]
account="devnet-rs"
network = "alpha-sepolia"
url = "http://127.0.0.1:5050"

